# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issue_comment
name: Comment trigger

on: issue_comment

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Comment Triggered Event"
