# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issues
name: Voting Automation for Content Management Project Board

on: issues

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Issue Triggered Event"
