# https://docs.github.com/en/rest/reference/projects#list-repository-projects
name: List projects from a repo

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Make API call
        uses: indiesdev/curl@v1
        id: api
        with: 
          headers: '{ "Accept": "application/vnd.github.inertia-preview+json" }' 
          url: https://api.github.com/repos/earnestdl/project-boards/projects
      - name: Use response
        run: echo ${{ steps.api.outputs.response }}
