# https://docs.github.com/en/rest/reference/projects#list-project-cards
name: list project cards from a column

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: list project cards
        run: echo "list project cards"