# https://docs.github.com/en/rest/reference/reactions
name: List reactions from an issue

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Make API call
        uses: indiesdev/curl@v1
        id: api
        with: 
          headers: '{ "Accept": "application/vnd.github.squirrel-girl-preview+json" }' 
          url: https://api.github.com/repos/earnestdl/project-boards/issues/1/reactions
      - name: Use response
        run: echo ${{ steps.api.outputs.response }}
