name: Test and Deploy
on: workflow_dispatch
jobs:
    run-unit-tests:
      runs-on: ${{ matrix.os }}
      timeout-minutes: 30
      strategy:
        fail-fast: false
        matrix:
          python-version: [3.7, 3.8]
          os: [macOS-latest, ubuntu-latest, windows-latest]
      name: ${{ matrix.os }} py${{ matrix.python-version }}
      steps:
        - uses: actions/checkout@v2
        - uses: s-weigand/setup-conda@v1.0.7
          name: Setup Conda
          with:
            python-version: ${{ matrix.python-version }}
            conda-channels: anaconda, conda-forge
            activate-conda: true
        - name: Check versions
          run: |
            conda --version
            which python
            python --version
            pwd
            ls
        - name: Upgrade pip
          run: |
            python -m pip install --upgrade pip

