name: Voting Automation for Content Management Project Board

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run python script
        working-directory: ./.github/workflows/scripts
        run: |
          python -m pip install -r requirements.txt
          python voting/voting.py
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
